name: "Continuous Integration"

on:
  push:
  pull_request:

jobs:
  build:

    name: Compile project and run tests (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 8
          - 11

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Fetch cached Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: maven-deps

      - name: Compile project, run tests
        run: |
          mvn --no-transfer-progress test

  docker:
    name: Build docker image
    needs: build

    if: ${{ github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH}}
          tags: "latest,${{ github.sha }}"

